repos:
- repo: https://github.com/Young-Naive-Simple/pre-commit-rust
  rev: 3a8de64acc969112746489e5ec1f0b13e00d871e
  hooks:
  - id: fmt
  - id: clippy
- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.10.0
  hooks:
  - id: pretty-format-yaml
    args: [--autofix, --indent, '2']
  - id: pretty-format-toml
    args: [--autofix, --indent, '2']
- repo: https://github.com/crate-ci/typos
  rev: v1.16.11
  hooks:
  - id: typos
